#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 13, 2017 12:09:32 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import devices_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    devices_support.set_Tk_var()
    top = Device_Attributes (root)
    devices_support.init(root, top)
    root.mainloop()

w = None
def create_Device_Attributes(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    devices_support.set_Tk_var()
    top = Device_Attributes (w)
    devices_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Device_Attributes():
    global w
    w.destroy()
    w = None


class Device_Attributes:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("507x428+487+145")
        top.title("Device Attributes")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.06, rely=0.07, relheight=0.76, relwidth=0.74)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=375)

        self.textIPaddress = Entry(self.Frame1)
        self.textIPaddress.place(relx=0.37, rely=0.25, relheight=0.06
                , relwidth=0.44)
        self.textIPaddress.configure(background="white")
        self.textIPaddress.configure(disabledforeground="#a3a3a3")
        self.textIPaddress.configure(font="TkFixedFont")
        self.textIPaddress.configure(foreground="#000000")
        self.textIPaddress.configure(highlightbackground="#d9d9d9")
        self.textIPaddress.configure(highlightcolor="black")
        self.textIPaddress.configure(insertbackground="black")
        self.textIPaddress.configure(selectbackground="#c4c4c4")
        self.textIPaddress.configure(selectforeground="black")
        self.textIPaddress.configure(textvariable=devices_support.ip_addr_input)
        self.textIPaddress.configure(validate="key")
        # get_ip() is called when a button is pressed
        self.textIPaddress.configure(validatecommand="get_ip")

        self.ipaddrLabel = Label(self.Frame1)
        self.ipaddrLabel.place(relx=0.16, rely=0.22, height=31, width=54)
        self.ipaddrLabel.configure(activebackground="#f9f9f9")
        self.ipaddrLabel.configure(activeforeground="black")
        self.ipaddrLabel.configure(background="#d9d9d9")
        self.ipaddrLabel.configure(disabledforeground="#a3a3a3")
        self.ipaddrLabel.configure(foreground="#000000")
        self.ipaddrLabel.configure(highlightbackground="#d9d9d9")
        self.ipaddrLabel.configure(highlightcolor="black")
        self.ipaddrLabel.configure(text='''IP address''')

        self.ButtonSave = Button(self.Frame1)
        self.ButtonSave.place(relx=0.13, rely=0.71, height=24, width=35)
        self.ButtonSave.configure(activebackground="#d9d9d9")
        self.ButtonSave.configure(activeforeground="#000000")
        self.ButtonSave.configure(background="#d9d9d9")
        self.ButtonSave.configure(command=devices_support.save)
        self.ButtonSave.configure(disabledforeground="#a3a3a3")
        self.ButtonSave.configure(foreground="#000000")
        self.ButtonSave.configure(highlightbackground="#d9d9d9")
        self.ButtonSave.configure(highlightcolor="black")
        self.ButtonSave.configure(pady="0")
        self.ButtonSave.configure(text='''Save''')

        self.Button2 = Button(self.Frame1)
        self.Button2.place(relx=0.29, rely=0.71, height=24, width=47)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Cancel''')

        self.Button3 = Button(self.Frame1)
        self.Button3.place(relx=0.51, rely=0.71, height=24, width=41)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Clear''')

        self.ButtonQuit_ = Button(self.Frame1)
        self.ButtonQuit_.place(relx=0.75, rely=0.71, height=24, width=34)
        self.ButtonQuit_.configure(activebackground="#d9d9d9")
        self.ButtonQuit_.configure(activeforeground="#000000")
        self.ButtonQuit_.configure(background="#d9d9d9")
        self.ButtonQuit_.configure(command=devices_support.quit)
        self.ButtonQuit_.configure(disabledforeground="#a3a3a3")
        self.ButtonQuit_.configure(foreground="#000000")
        self.ButtonQuit_.configure(highlightbackground="#d9d9d9")
        self.ButtonQuit_.configure(highlightcolor="black")
        self.ButtonQuit_.configure(pady="0")
        self.ButtonQuit_.configure(text='''Quit''')






if __name__ == '__main__':
    vp_start_gui()



