#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 13, 2017 12:09:43 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global ip_addr_input
    ip_addr_input = StringVar()
    print("set_Tk_var")

def quit():
    print('devices_support.quit')
    sys.stdout.flush()

def save():
    print('devices_support.save')
    print(ip_addr_input.get())
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import devices
    devices.vp_start_gui()


