#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 21, 2017 08:35:37 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import sample1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    sample1_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    sample1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("549x471+429+162")
        top.title("New Toplevel 1")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.07, rely=0.13, relheight=0.69, relwidth=0.74)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=405)

        self.okbutton = Button(self.Frame1)
        self.okbutton.place(relx=0.1, rely=0.43, height=34, width=97)
        self.okbutton.configure(activebackground="#d9d9d9")
        self.okbutton.configure(activeforeground="#000000")
        self.okbutton.configure(background="#d9d9d9")
        self.okbutton.configure(command=sample1_support.ok_callback)
        self.okbutton.configure(disabledforeground="#a3a3a3")
        self.okbutton.configure(foreground="#000000")
        self.okbutton.configure(highlightbackground="#d9d9d9")
        self.okbutton.configure(highlightcolor="black")
        self.okbutton.configure(pady="0")
        self.okbutton.configure(text='''OK''')
        self.okbutton.configure(width=97)

        self.textfield = Entry(self.Frame1)
        self.textfield.place(relx=0.1, rely=0.22, relheight=0.06, relwidth=0.45)
        self.textfield.configure(background="white")
        self.textfield.configure(disabledforeground="#a3a3a3")
        self.textfield.configure(font="TkFixedFont")
        self.textfield.configure(foreground="#000000")
        self.textfield.configure(insertbackground="black")
        self.textfield.configure(validatecommand="validate_callback")
        self.textfield.configure(width=184)

        self.textlabel = Label(self.Frame1)
        self.textlabel.place(relx=0.15, rely=0.06, height=31, width=74)
        self.textlabel.configure(background="#d9d9d9")
        self.textlabel.configure(disabledforeground="#a3a3a3")
        self.textlabel.configure(foreground="#000000")
        self.textlabel.configure(text='''Input field''')
        self.textlabel.configure(width=74)

        self.cancelbutton = Button(self.Frame1)
        self.cancelbutton.place(relx=0.52, rely=0.43, height=34, width=77)
        self.cancelbutton.configure(activebackground="#d9d9d9")
        self.cancelbutton.configure(activeforeground="#000000")
        self.cancelbutton.configure(background="#d9d9d9")
        self.cancelbutton.configure(command=sample1_support.cancel_callback)
        self.cancelbutton.configure(disabledforeground="#a3a3a3")
        self.cancelbutton.configure(foreground="#000000")
        self.cancelbutton.configure(highlightbackground="#d9d9d9")
        self.cancelbutton.configure(highlightcolor="black")
        self.cancelbutton.configure(pady="0")
        self.cancelbutton.configure(text='''Cancel''')
        self.cancelbutton.configure(width=77)






if __name__ == '__main__':
    vp_start_gui()



