#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 21, 2017 08:22:33 PM
#    Sep 21, 2017 08:36:43 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1




def cancel_callback():
    print('sample1_support.cancel_callback')
    sys.stdout.flush()


def ok_callback():
    print('sample1_support.ok_callback')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import sample1
    sample1.vp_start_gui()





