#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Dec 05, 2017 05:04:44 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

import tkinter

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    text = "Text from scroll_text_support.init"
    w.Scrolledtext1.insert(tkinter.INSERT, text)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import scroll_text
    scroll_text.vp_start_gui()


